"""Build stats tables from runs of the authors' MAIN.py.

Parses every log in pennylane_reproduction/logs/ named
<YYYY-MM-DD>_<as_released|paper_config>_<models>.log (console captures
ending in _console.log are skipped; they duplicate the structured logs),
and writes:

    results/stats_summary.csv   one row per (run, model), every statistic
    results/stats_summary.md    readable tables: per-run results,
                                reproducibility, comparison with the paper

Note: the authors' logger labels the interquartile range (75th minus 25th
percentile across the 7 folds) as "std". It is reported here as IQR.

Usage (from repo root):
    $PY pennylane_reproduction/summarize_runs.py
"""
import re
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
LOGS = HERE / "logs"
RESULTS = HERE / "results"

MODEL_NAMES = {
    "Naive Baseline: Equal Weights Model": "Equal Weights",
    "Mean-Variance Optimization": "Mean-Variance Optimization",
    "Deep Deterministic Policy Gradient": "DDPG",
    "Quantum Deterministic Policy Gradient": "QDPG",
    "Deep Q-Learning": "Deep Q-Learning",
    "Quantum Q-Learning": "Quantum Q-Learning",
}
MODEL_ORDER = list(MODEL_NAMES.values())

# Paper Table 5.1 (arXiv:2601.18811): mean Sharpe (std across 7 folds).
# Headline metric: static (SPO) for Equal Weights / MVO, dynamic (DPO) for RL.
PAPER = {
    "Equal Weights": ("SPO", 0.4375, 0.6558, "Equal Weights Portfolio"),
    "Mean-Variance Optimization": ("SPO", 0.5919, 0.9170, "Mean-Variance Optimization"),
    "DDPG": ("DPO", 0.4384, 0.6905, "Classical DDPG, 27k params (nearest tier; code has 34k)"),
    "QDPG": ("DPO", 0.7281, 0.7395, "Quantum DDPG, 60 params"),
    "Deep Q-Learning": ("DPO", 0.4939, 0.6623, "Classical DQN, 27k params (nearest tier; code has 34k)"),
    "Quantum Q-Learning": ("DPO", 0.6537, 0.6155, "Quantum DQN, 60 params"),
}

SECTION_RE = re.compile(r"^-{20,}\n(.+?)\n-{20,}$", re.M)
METRIC_RE = re.compile(
    r"Average (Profit p\.a\.|Sharpe Ratio) \((SPO|DPO)\):\s*([-\d.]+)\s*%?\s*"
    r"\(std: ([-\d.]+), min: ([-\d.]+), max: ([-\d.]+)\)")
TIME_RE = re.compile(r"Execution time: (.+)")
UNIT_RE = re.compile(r"([\d.]+)\s*(hour|minute|second)s?")
UNIT_SECONDS = {"hour": 3600, "minute": 60, "second": 1}


def to_seconds(timespan: str) -> float:
    return sum(float(n) * UNIT_SECONDS[u] for n, u in UNIT_RE.findall(timespan))


def parse_log(path: Path) -> list:
    date, config = path.stem.split("_")[0], (
        "paper_config" if "_paper_config_" in path.name else "as_released")
    text = path.read_text(errors="replace")
    titles = list(SECTION_RE.finditer(text))
    rows = []
    for i, match in enumerate(titles):
        title = match.group(1).strip()
        if title not in MODEL_NAMES:
            continue
        end = titles[i + 1].start() if i + 1 < len(titles) else len(text)
        body = text[match.end():end]
        stats = {}
        for metric, mode, mean, iqr, lo, hi in METRIC_RE.findall(body):
            key = f"{mode.lower()}_{'profit_pct' if metric.startswith('Profit') else 'sharpe'}"
            stats.update({key: float(mean), f"{key}_iqr": float(iqr),
                          f"{key}_min": float(lo), f"{key}_max": float(hi)})
        if not stats:
            continue  # section present but run did not finish
        time_match = TIME_RE.search(body)
        rows.append({"run_date": date, "config": config, "log": path.name,
                     "model": MODEL_NAMES[title],
                     "runtime_s": to_seconds(time_match.group(1)) if time_match else None,
                     **stats})
    return rows


def fmt(x, nd=4):
    return "—" if pd.isna(x) else f"{x:.{nd}f}"


def fmt_time(s):
    if pd.isna(s):
        return "—"
    h, rem = divmod(int(round(s)), 3600)
    m, sec = divmod(rem, 60)
    return f"{h}h {m}m" if h else (f"{m}m {sec}s" if m else f"{s:.1f}s")


def main():
    logs = sorted(p for p in LOGS.glob("*.log") if not p.name.endswith("_console.log"))
    df = pd.DataFrame([r for p in logs for r in parse_log(p)])
    df["model"] = pd.Categorical(df["model"], MODEL_ORDER, ordered=True)
    df = df.sort_values(["config", "run_date", "model"]).reset_index(drop=True)

    RESULTS.mkdir(exist_ok=True)
    df.to_csv(RESULTS / "stats_summary.csv", index=False)

    md = ["# Authors' PennyLane code: run statistics", "",
          "Generated by `summarize_runs.py` from the logs in `logs/`. All values are",
          "across the 7 time-series cross-validation folds. **IQR** is the",
          "interquartile range (the authors' logger mislabels it as \"std\").",
          "SPO = static allocation, DPO = rebalanced every 30 days.", ""]

    md += ["## 1. Results per run", ""]
    for (config, date), run in df.groupby(["config", "run_date"], observed=True):
        md += [f"### {date} — {config.replace('_', ' ')}", "",
               "| Model | SPO profit p.a. | SPO Sharpe (IQR, min…max) | DPO profit p.a. | DPO Sharpe (IQR, min…max) | Runtime |",
               "|---|---|---|---|---|---|"]
        for _, r in run.iterrows():
            spo_s = f"{fmt(r.get('spo_sharpe'))} ({fmt(r.get('spo_sharpe_iqr'))}, {fmt(r.get('spo_sharpe_min'))}…{fmt(r.get('spo_sharpe_max'))})"
            dpo_s = (f"{fmt(r.get('dpo_sharpe'))} ({fmt(r.get('dpo_sharpe_iqr'))}, {fmt(r.get('dpo_sharpe_min'))}…{fmt(r.get('dpo_sharpe_max'))})"
                     if not pd.isna(r.get("dpo_sharpe")) else "—")
            dpo_p = f"{fmt(r.get('dpo_profit_pct'), 2)}%" if not pd.isna(r.get("dpo_profit_pct")) else "—"
            md.append(f"| {r['model']} | {fmt(r['spo_profit_pct'], 2)}% | {spo_s} | {dpo_p} | {dpo_s} | {fmt_time(r['runtime_s'])} |")
        md.append("")

    md += ["## 2. Reproducibility (same model and config, different dates)", "",
           "| Model | Config | Dates compared | All statistics identical? |", "|---|---|---|---|"]
    stat_cols = [c for c in df.columns if c.startswith(("spo_", "dpo_"))]
    any_pairs = False
    for (model, config), grp in df.groupby(["model", "config"], observed=True):
        if grp["run_date"].nunique() < 2:
            continue
        any_pairs = True
        vals = grp[stat_cols].round(6)
        same = bool((vals.nunique(dropna=False) <= 1).all())
        md.append(f"| {model} | {config.replace('_', ' ')} | {', '.join(sorted(grp['run_date']))} | {'yes, to every printed digit' if same else 'NO'} |")
    if not any_pairs:
        md.append("| — | — | — | no repeated runs yet |")
    md.append("")

    md += ["## 3. Headline Sharpe vs. the paper (Table 5.1)", "",
           "Latest run of each config. Paper values include 0.15% transaction costs; "
           "the code's metric has none, which would push the code's numbers *above* the paper's.", "",
           "| Model | Metric | As released | Paper config | Paper | Paper row |", "|---|---|---|---|---|---|"]
    latest = df.sort_values("run_date").groupby(["model", "config"], observed=True).tail(1)
    for model in MODEL_ORDER:
        mode, p_mean, p_std, p_row = PAPER[model]
        col = f"{mode.lower()}_sharpe"
        def pick(cfg):
            hit = latest[(latest["model"] == model) & (latest["config"] == cfg)]
            return hit[col].iloc[0] if len(hit) else float("nan")
        paper_cfg = pick("paper_config")
        if pd.isna(paper_cfg) and model in ("Equal Weights", "Mean-Variance Optimization"):
            paper_cfg_txt = "same (no training)"
        elif pd.isna(paper_cfg):
            paper_cfg_txt = "not run yet"
        else:
            paper_cfg_txt = fmt(paper_cfg)
        md.append(f"| {model} | {mode} Sharpe | {fmt(pick('as_released'))} | {paper_cfg_txt} | "
                  f"{p_mean:.4f} (std {p_std:.4f}) | {p_row} |")
    md.append("")

    (RESULTS / "stats_summary.md").write_text("\n".join(md))
    print(f"Parsed {len(logs)} logs, {len(df)} model runs")
    print(f"Wrote {RESULTS / 'stats_summary.csv'} and {RESULTS / 'stats_summary.md'}")


if __name__ == "__main__":
    main()
